# Generated by Django 5.1.5 on 2025-01-24 08:14

from django.db import migrations, models

def set_default_name(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(name__isnull=True).update(name='default_name')              

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_name),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, null=False),
        ),
    ]
